- name: Get Private IP
  hosts: localhost
  become: true
  gather_facts: false
  tasks:
    - name: Get IP Address
      shell: virsh domifaddr k8s | grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b'
      register: defined_vm_ip_result
      until: "defined_vm_ip_result is success"
      retries: 30
      delay: 5
    - name: Print result variable
      debug:
        msg:
          - "{{ defined_vm_ip_result.stdout }}"
    - name: restore ip address
      shell: echo {{ defined_vm_ip_result.stdout }} >> /home/k/hii.txt
      retries: 20
